[tool.mypy]
files = ["streamfarer"]
strict = true
disallow_any_expr = true
disallow_any_decorated = true
disallow_any_explicit = true
plugins = ["pydantic.mypy"]

[tool.pydantic-mypy]
init_typed = true
init_forbid_extra = true

[tool.pylint.main]
disable = [
    # Good design is best figured out by humans yet
    "design", "too-many-lines", "too-many-nested-blocks",
    # Handled by mypy
    "classes", "typecheck"
]
jobs = 0
output-format = "colorized"
