name: Check Code
on:
    - push
    - pull_request
jobs:
    check:
        strategy:
            matrix:
                python:
                    - "3.11"
                    - "3.12"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python }}
            - env:
                  VERSION: "1.1.24"
              run: |
                  curl --location --silent https://github.com/twitchdev/twitch-cli/releases/download/v${VERSION}/twitch-cli_${VERSION}_Linux_x86_64.tar.gz | \
                      tar --extract --gzip
                  echo twitch-cli_${VERSION}_Linux_x86_64 >> $GITHUB_PATH
            - run: make dependencies dependencies-dev
            - run: make type
            - run: make test
            - run: make lint PYLINTFLAGS=--output-format=github
              continue-on-error: ${{ contains(github.event.head_commit.message, 'WIP') }}
